### ISSUE TITLE
Parameters of elements are visualized incorrectly if using browser google chrome on Windows and set the window zoom more then 150%. Or if using mobile gadgets.

### ISSUE THREAD

**Issue by Ladone3** [ontodia-org/ontodia#25]
The main problem is that content of element (foreignObject) inside svg, rendered outside if using overflow: scroll or position: relative, absolute e.t.c.
Related chrome issues:
https://bugs.chromium.org/p/chromium/issues/detail?id=568614
https://bugs.chromium.org/p/chromium/issues/detail?id=578682
For now it's true only for google chrome (tested on v. 57.0.2970.0). Opera(v. 42.0.2393.94), IE(11/Edge) and Firefox(v. 47.0.1) are working fine with scrolling (not with position).

**Comment by yuricus** [comment]
Actually we faced some other reports of this, For example, under Mac OS and Safari 10.0.2 (12602.3.12.0.1) and Chrome 55.0.2883.95 (64-bit) with default zoom settings in browser.
