### ISSUE TITLE
can I edit the graph?

### ISSUE THREAD

**Issue by ChipNowacek** [ontodia-org/ontodia#47]
Can I edit? How difficult would it be to add the facility?

**Comment by DpavlovPavlovD** [comment]
Hi Chip!
Thanks for the feature request!

I perfectly understand your concern. The second natural things you'd like to do with visualization is try to change the graph. 

This functionality is in our development plans. We estimate the scope of this task as 1 developer month. But it is hard in our small team engaged in custom development to find such a long stretch of time to pull the developer out of ongoing projects. We would certainly appreciate any contribution that could move us all in this direction. 

Quite some time ago we've made a very rough prototype for visual data editing - http://ontodia.org/news/semantic-data-editing-sneak-preview. 
The demo is still online and could be accessed here (please allow some time for the virtual machine to kick in): edit.ontodia.org
As a disclaimer I should say that currently this particular demo shoots sparql update queries and the only case for the changes to be persisted into the data is when data is coming from SPARQL endpoint with permissions to write. 

Here's a small screencast that we made to come with the demo: https://www.youtube.com/watch?v=lfacnqCSzTM&t=155s

Please let me know if it answers your question. 
I'd be happy to continue the discussion over email (dmitry.pavlov@vismart.biz) or in our slack channel. May I use the email address listed in your github profile to invite you to our slack community?

**Comment by DpavlovPavlovD** [comment]
Hi Chip!
Right now we are stepping to development of data authoring and data editing. Would be glad to hear your advice and your vision of this feature!

**Comment by AlexeyMz** [comment]
Implemented in v0.9.0.
